### ISSUE TITLE
Add units to Bush Tracker fields

### ISSUE THREAD

**Issue by robroyaus** [russellwwest/bushdivers#66]
As reported in Discord, it can be confusing to use the BushDiverTracker app to accept a flight because fuel and cargo weights don't match between the app and the sim. This is particularly likely when your sim settings are metric (kg and litres) because the BushDiverTracker app expects pounds and gallons.

Adding the units (lb, gal) for all entry fields would be a simple way to signpost which units are expected.

For bonus points, add text saying something like "Please select "U.S. System" in Options | General Options | Misc | International Settings"

**Comment by russellwwest** [comment]
Fixed
